<div class="footer-bottom-copyright">
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-bottom-copyright')
        ->toHtml();
    ?>
</div>

<div class="footer-bottom-method-payment">
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-bottom-payment')
        ->toHtml();
    ?>
</div>