<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter footer-mid">
    <div>
        <h3 class="title-footer">Newsletter</h3>
        <p>Subscribe to our newsletter for the latest
            news and updates</p>
    </div>
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />                        
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('>')) ?></span>
                </button>
            </div>            
        </form>
    </div>
    <div class="social">
        <div class="social-icon-facebook"><a href="#"><i class="fab fa-facebook-f"></i></a></div>
        <div class="social-icon-instagram"><a href="#"><i class="fab fa-instagram"></i></a></div>
        <div class="social-icon-twitter"><a href="#"><i class="fab fa-twitter"></i></a></div>
        <div class="social-icon-twitter"><a href="#"><i class="fab fa-youtube"></i></a></div>
        <div class="social-icon-twitter"><a href="#"><i class="fab fa-pinterest"></i></a></div>
    </div>                
</div>
